name:  Merge Draft
on: push

jobs:
    build:
        name: update source
        runs-on: ubuntu-latest
        steps:
            - name: run update script
              uses: actions/checkout@v1
              run: sudo bash update.sh
