name:  Merge Draft
on: push

jobs:
    build:
        name: update source
        runs-on: ubuntu-latest
        steps:
            - name: Hello World
              uses: actions/checkout@v2
              run: echo "Hello World"
